version: '2'
services:
  app:
    image: golang:1.8-alpine
    container_name: meli_app
    ports:
    - "80:8080"
    links:
    - mysql
    volumes:
    - .:/go/src/meli
    working_dir: /go/src/meli
    command: go run main.go
    environment:
      PORT: '8080'

  mysql:
    image: mysql
    container_name: meli_mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: meli
      MYSQL_PASSWORD: meli
      MYSQL_DATABASE: meli
